### ISSUE TITLE
Blind Pest destroying this character

### ISSUE THREAD

**Issue by Zero000002** [Popcorn-Factory/lee-hyperreal-ror2#2]
If it's not too much to ask, could you add a configuration option where I can increase defense/decrease damage taken? Because in the stages where the Blind Pest appear, they are a real hell. There's literally not much to do other than try to distance yourself from them to shoot from afar, and usually while I try to do that, more and more of them appear. They are the only enemies that REALLY get in my way when playing with this character.

**Comment by Zero000002** [comment]
or an alternative skill where I can use the rifle while moving that would help too

**Comment by Ethanol10** [comment]
You should be able to parry the projectile back towards them, alternatively you can bait them lower to the ground and hit them with Armament Barrage 4. But yeah, it's an inherent design choice. 

The rifle also can be cancelled using Jump or Sprint, consider using that to your advantage!

**Comment by Zero000002** [comment]
> You should be able to parry the projectile back towards them, alternatively you can bait them lower to the ground and hit them with Armament Barrage 4. But yeah, it's an inherent design choice.
> 
> The rifle also can be cancelled using Jump or Sprint, consider using that to your advantage!

The problem with parry is that the character's attack animation is very "exaggerated". If it were simpler, like using the rifle to hit enemies and I could control the direction of the character, like the mercenary, using the sword even with him attacking I have control over him when he attacks, I feel like this mod was designed to play with a controller and I don't have any at the moment.

**Comment by Ethanol10** [comment]
Well, it was designed with the animations in focus, I think it's mostly a matter of using the invincible frames during orb moves and dodge to wipe out enemies. You should not need a controller to play this character, as all the attack buttons are clustered around the movement (1,2,3,R,Shift,M1, M2). Parries and invincibility frames make or break runs, so you'll have to completely leverage that.
