### ISSUE TITLE
No. of Skill Orbs goes above 16

### ISSUE THREAD

**Issue by Anhilliator1** [Popcorn-Factory/lee-hyperreal-ror2#3]
Not sure if intended, but under certain circumstances the number of orbs can go above 16. When it happened to me, I couldn't actually ping any orbs for a few seconds.

**Comment by Ethanol10** [comment]
Hmm, Sounds like two separate things. For one, going over 16 is intended when you use coloured bullets to retrieve more orbs to use. 

However, not being able to ping orbs for a few seconds is another issue. However, it should be fixed in the latest version.

Let me know if this issue persists!
